# Generated by Django 2.2.7 on 2019-11-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sla_number', models.CharField(max_length=255)),
                ('kpi_read', models.IntegerField(max_length=25)),
                ('next_kpi', models.CharField(max_length=255)),
            ],
        ),
    ]
