# Generated by Django 2.2.7 on 2019-11-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_kpi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='kpi_read',
            field=models.IntegerField(),
        ),
    ]
