# Generated by Django 2.2.7 on 2019-11-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20191107_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sla',
            name='sla_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
