# Generated by Django 2.2.7 on 2019-11-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_rules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sla',
            name='kpi_threshold',
        ),
    ]
