# Generated by Django 2.2.6 on 2019-11-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20191107_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='sla',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
